# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Generator

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/20 * * * *'  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pathlib

    - name: DataGenerate
      run: |
        python ./data.py

    - name: Pushes S1B folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: S1B
        destination_repo: TomoeMami/tomoemami.github.io
        destination_folder: S1B
        user_email: 'trembleafterme@outlook.com'
        user_name: 'TomoeMami'
        commit_msg: '[GHA] Update the S1G files.'
